[package]
name = "rmonkey"
version = "0.1.0"
authors = ["kdnakt <a.kid.1985@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
